/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author victor
 */
public class ScoreBoard extends javax.swing.JPanel {
    
    private int score;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        incrementScore(0);
    }
    
    public void incrementScore(int increment) {
        score += increment;
        scoreLabel.setText("Score for " + 
                Config.getInstance().getPlayerName() + 
                ": " + score);
    }
    
    public void setScore(int score) {
        this.score = score;
        incrementScore(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();

        scoreLabel.setText("Score: 0");
        add(scoreLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
